### ISSUE TITLE
"python bin/DeepMod.py detect" produces error

### ISSUE THREAD

**Issue by ViHammer** [WGLab/DeepMod#41]
The command ```python bin/DeepMod.py detect```, mentioned under "Install DeepMod" throws a TypeError:

```
(mdeepmod) /.../DeepMod$ python bin/DeepMod.py detect
No mod file is provided. The default one is used
Traceback (most recent call last):
  File "bin/DeepMod.py", line 383, in <module>
    args.func(args);
  File "bin/DeepMod.py", line 140, in mDetect
    moptions['modfile'] = ('{}/lib/python{}.{}/site-packages/DeepMod/train_deepmod/rnn_P90wd%d_f53/mod_train_P90wd%d_f53' % (sys.prefix,sys.version_info.major,sys.version_info.minor, moptions['windowsize'], moptions['windowsize']))
TypeError: %d format: a number is required, not str
```

**Comment by liuqianhn** [comment]
@ViHammer My fault. I made the correction. Pleased download the updated "bin/DeepMod.py".

**Comment by ViHammer** [comment]
> 
> 
> @ViHammer My fault. I made the correction. Pleased download the updated "bin/DeepMod.py".

Works now!
