### ISSUE TITLE
Any help appreciated with very cryptic errors

### ISSUE THREAD

**Issue by Arkadiy-Garber** [WGLab/DeepMod#60]
```
Command: python /data/MAB/bin/DeepMod2/deepmod2 detect-guppy --threads 24 --fast5 ../../../fast5_pass/single_barcode12 --ref assembly.fasta --bam assembly.bam

RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
2023-04-07 18:34:06.018981: Number of files: 110340

2023-04-07 18:34:06.078891: Processing BAM File.
2023-04-07 18:44:13.873240: Finished Processing BAM File.
2023-04-07 18:44:13.873400: Starting Per Read Methylation Detection.
2023-04-07 18:44:17.356034: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/data/MAB/miniconda3/envs/deepmod2/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/data/MAB/bin/DeepMod2/src/guppy.py", line 176, in detect
    base_level_data, seq_len, mean_qscore, sequence_length = get_read_signal(read, params['guppy_group'])
  File "/data/MAB/bin/DeepMod2/src/guppy.py", line 121, in get_read_signal
    segment=read.get_analysis_attributes(guppy_group)['segmentation']
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/MAB/bin/DeepMod2/deepmod2", line 150, in <module>
    run(params)
  File "/data/MAB/bin/DeepMod2/deepmod2", line 11, in run
    read_pred_file=modDetect.per_read_predict(params)
  File "/data/MAB/bin/DeepMod2/src/modDetect.py", line 59, in per_read_predict
    file_list=[file_name for file_name in res]
  File "/data/MAB/bin/DeepMod2/src/modDetect.py", line 59, in <listcomp>
    file_list=[file_name for file_name in res]
  File "/data/MAB/miniconda3/envs/deepmod2/lib/python3.9/multiprocessing/pool.py", line 870, in next
    raise value
TypeError: 'NoneType' object is not subscriptable

```

Thanks,
Arkadiy

**Comment by kaichop** [comment]
if you are using deepmod2 please post the issue to deepmod2's repository.
